services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app  # Mount local files
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "5173:5173"  # Vite default port
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run dev --host"
