services:
  frontend:
    image: node:18-alpine  # Use Node.js for development
    working_dir: /app
    volumes:
      - ./frontend:/app  # Mount the frontend folder
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "5173:5173"  # Map Vite's default port
    command: sh -c "npm run dev -- --host"
